import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import {
  LucideAngularModule,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  ArrowDown,
  Check,
  ChevronRight,
  ChevronDown,
  Plus,
  X,
  Menu,
  Home,
  CalendarDays,
  Target,
  Folder,
  ListTodo,
  Sprout,
  FlaskConical,
  Flag,
  Map,
  Users,
  Swords,
  ChartNoAxesCombined,
  Gift,
  Award,
  Bell,
  Settings,
  CircleHelp,
  MessageSquare,
  LogOut,
  Search,
  Sun,
  Moon,
  Heart,
  Sparkles,
  Flame,
  Zap,
  Coffee,
  BookOpen,
  Clapperboard,
  Mountain,
  Footprints,
  Shield,
  Activity,
  MoreHorizontal,
  Globe,
  LockKeyhole,
  Mail,
  CircleCheck,
  CircleAlert,
  RefreshCw,
  Download,
  ArrowUp,
  Compass,
  Leaf,
  Circle,
} from 'lucide-angular';
const icons = {
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  'arrow-down': ArrowDown,
  check: Check,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  plus: Plus,
  x: X,
  menu: Menu,
  home: Home,
  calendar: CalendarDays,
  target: Target,
  folder: Folder,
  tasks: ListTodo,
  sprout: Sprout,
  flask: FlaskConical,
  flag: Flag,
  map: Map,
  users: Users,
  swords: Swords,
  chart: ChartNoAxesCombined,
  gift: Gift,
  award: Award,
  bell: Bell,
  settings: Settings,
  help: CircleHelp,
  message: MessageSquare,
  logout: LogOut,
  search: Search,
  sun: Sun,
  moon: Moon,
  heart: Heart,
  sparkles: Sparkles,
  flame: Flame,
  zap: Zap,
  coffee: Coffee,
  'book-open': BookOpen,
  clapperboard: Clapperboard,
  mountain: Mountain,
  footprints: Footprints,
  shield: Shield,
  activity: Activity,
  more: MoreHorizontal,
  globe: Globe,
  lock: LockKeyhole,
  mail: Mail,
  'circle-check': CircleCheck,
  alert: CircleAlert,
  refresh: RefreshCw,
  download: Download,
  'arrow-up': ArrowUp,
  compass: Compass,
  leaf: Leaf,
};
@Component({
  selector: 'lq-icon',
  imports: [LucideAngularModule],
  template:
    '<lucide-icon [img]="icon()" [size]="size()" [strokeWidth]="1.7" aria-hidden="true" class="block" />',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'inline-flex shrink-0 align-middle' },
})
export class Icon {
  readonly name = input('circle');
  readonly size = input(20);
  icon() {
    return icons[this.name() as keyof typeof icons] ?? Circle;
  }
}
