ALTER TABLE "XPTransaction" ADD CONSTRAINT xp_amount_positive CHECK (amount > 0);
ALTER TABLE "Reward" ADD CONSTRAINT reward_cost_positive CHECK (cost > 0), ADD CONSTRAINT reward_limit_positive CHECK ("redemptionLimit" IS NULL OR "redemptionLimit" > 0);
ALTER TABLE "RewardRedemption" ADD CONSTRAINT redemption_cost_positive CHECK ("costSnapshot" > 0);
ALTER TABLE "DailyCheckIn" ADD CONSTRAINT mood_range CHECK (mood BETWEEN 1 AND 5), ADD CONSTRAINT energy_range CHECK (energy BETWEEN 1 AND 5);
ALTER TABLE "Habit" ADD CONSTRAINT habit_target_positive CHECK (target > 0), ADD CONSTRAINT weekly_target_range CHECK ("weeklyTarget" BETWEEN 1 AND 7);
ALTER TABLE "HabitLog" ADD CONSTRAINT habit_log_value_positive CHECK (value > 0), ADD CONSTRAINT habit_target_snapshot_positive CHECK ("targetSnapshot" > 0);
ALTER TABLE "Goal" ADD CONSTRAINT goal_progress_range CHECK ("manualProgress" BETWEEN 0 AND 100), ADD CONSTRAINT goal_numeric_target_positive CHECK ("numericTarget" IS NULL OR "numericTarget" > 0), ADD CONSTRAINT goal_value_nonnegative CHECK ("numericValue" >= 0);
ALTER TABLE "Challenge" ADD CONSTRAINT challenge_date_order CHECK ("endDate" > "startDate");
ALTER TABLE "ChallengeRule" ADD CONSTRAINT challenge_target_positive CHECK (target > 0), ADD CONSTRAINT challenge_cap_positive CHECK ("dailyCap" > 0);
ALTER TABLE "Friendship" ADD CONSTRAINT friendship_no_self CHECK ("senderId" <> "receiverId"), ADD CONSTRAINT friendship_blocker_participant CHECK ("blockedById" IS NULL OR "blockedById" IN ("senderId", "receiverId"));
ALTER TABLE "Milestone" ADD CONSTRAINT milestone_one_parent CHECK (("goalId" IS NULL) <> ("projectId" IS NULL));
ALTER TABLE "SeasonPhase" ADD CONSTRAINT phase_month_range CHECK (month BETWEEN 1 AND 12);
ALTER TABLE "MonthJourney" ADD CONSTRAINT journey_month_range CHECK (month BETWEEN 1 AND 12);
CREATE FUNCTION lifequest_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only records cannot be altered'; END; $$;
CREATE TRIGGER xp_append_only BEFORE UPDATE OR DELETE ON "XPTransaction" FOR EACH ROW EXECUTE FUNCTION lifequest_append_only();
CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION lifequest_append_only();
CREATE FUNCTION lifequest_freeze_rules() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD."frozenAt" IS NOT NULL THEN RAISE EXCEPTION 'Active challenge rules are immutable'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER challenge_frozen_rules BEFORE UPDATE ON "ChallengeRule" FOR EACH ROW EXECUTE FUNCTION lifequest_freeze_rules();
CREATE FUNCTION lifequest_freeze_baseline() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD."baselineEnd" IS NOT NULL AND (NEW.baseline IS DISTINCT FROM OLD.baseline OR NEW."baselineStart" IS DISTINCT FROM OLD."baselineStart" OR NEW."baselineEnd" IS DISTINCT FROM OLD."baselineEnd" OR NEW."habitId" IS DISTINCT FROM OLD."habitId") THEN RAISE EXCEPTION 'Baseline snapshots are immutable'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER challenge_frozen_baseline BEFORE UPDATE ON "ChallengeParticipant" FOR EACH ROW EXECUTE FUNCTION lifequest_freeze_baseline();
CREATE FUNCTION lifequest_freeze_score() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.final THEN RAISE EXCEPTION 'Final challenge results are immutable'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER challenge_final_score BEFORE UPDATE OR DELETE ON "ChallengeScore" FOR EACH ROW EXECUTE FUNCTION lifequest_freeze_score();
